### ISSUE TITLE
What's the status?

### ISSUE THREAD

**Issue by FezVrasta** [gilt/postcss-less#1]
Is this project ready for production?

**Comment by bfosterscripps** [comment]
+1 - what is the status on this?

**Comment by shellscape** [comment]
(Didn't have my notifications for this repo going to the right place!)

@FezVrasta @bfosterscripps 
It's in development at the moment, and we're welcoming contribution. Our main motivation for the effort is to couple it with [lesshint](https://github.com/lesshint/lesshint)

Whether or not it's production-ready is going to depend on your exact needs and implementation. PostCSS already covers *alot* of the valid syntax that LESS uses, but as you can see from the commits we've had to add some additional support. We'll eventually have a comprehensive test suite setup to cover all of LESS' features, but for now it's touch and go.

**Comment by FezVrasta** [comment]
Thank you, I'll probably give it a try

**Comment by shellscape** [comment]
This project is not being actively maintained at the moment. Should that change, I'll follow up on this issue. For now, we recommend https://github.com/webschik/postcss-less
