### ISSUE TITLE
Documentation tuning

### ISSUE THREAD

**Issue by paazmaya** [gilt/postcss-less#2]
Perhaps the `README.md` could be updated to say LESS in the places where Sass or SCSS is currenctly being referred.

Also the code examples could be fixed so that the correct configuration for PostCSS `process` method is given. Based on the exported object in `dist/less-syntax.js`:

```js
postcss().process(less, {
    from: filepath,
    syntax: syntax.default
  }).then(function (result) {
    result.content // LESS with transformations
});
```

**Comment by shellscape** [comment]
this project is definitely a work in progress. those sound like great updates, please do submit a PR

**Comment by shellscape** [comment]
This project is not being actively maintained at the moment. Should that change, I'll follow up on this issue. For now, we recommend https://github.com/webschik/postcss-less
